# Generated by Django 4.1.2 on 2022-10-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0002_alter_universitycampus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitycampus',
            options={},
        ),
    ]
