# Generated by Django 4.1.2 on 2022-10-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0003_alter_universitycampus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitycampus',
            options={'verbose_name_plural': 'University Campus'},
        ),
    ]
