# Generated by Django 4.1.2 on 2022-10-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0004_alter_universitycampus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitycampus',
            options={},
        ),
    ]
